name: Deploy Next.js site to Vercel

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set VERCEL_INTERACTIVE to 0
        run: echo 'export VERCEL_INTERACTIVE=0' >> $GITHUB_ENV

      - name: Deploy to Vercel
        run: |
          vercel deploy --token $VERCEL_TOKEN --prod
